scope: ha-cluster
name: patroni
namespace: /service/

restapi:
  listen: 0.0.0.0:8008
  connect_address: 127.0.0.1:8008

etcd3:
  hosts: 127.0.0.1:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      parameters:
        max_connections: 100
        max_wal_senders: 5
        max_replication_slots: 5
        wal_level: replica
        hot_standby: "on"
        wal_log_hints: "on"

postgresql:
  listen: 0.0.0.0:5432
  connect_address: 127.0.0.1:5432
  data_dir: /data/postgres
  bin_dir: /usr/lib/postgresql/16/bin
  authentication:
    superuser:
      username: postgres
      password: postgres
    replication:
      username: replicator
      password: replicate
  pg_hba:
  - local all all trust
  - host all all 0.0.0.0/0 md5
  - host replication replicator 0.0.0.0/0 md5
  parameters:
    unix_socket_directories: /var/run/postgresql
